# Default config file for naive bayes. Please see sklearn.naive_bayes.MultinomialNB documentation for description of model params.
model_params:
    alpha: 1.0
    fit_prior: True
    class_prior: null