# Default config file for random forest. Please see sklearn.ensemble.RandomForestClassifier documentation for description of model params.
model_params:
    n_estimators: 100
    criterion: gini
    max_depth: null
    min_samples_split: 2
    min_samples_leaf: 1
    min_weight_fraction_leaf: 0.0
    max_features: sqrt
    max_leaf_nodes: null
    min_impurity_decrease: 0.0
    bootstrap: True
    oob_score: False
    n_jobs: null
    random_state: null
    verbose: 0
    warm_start: False
    class_weight: null
    ccp_alpha: 0.0
    max_samples: null