# Default config file for svm. Please see sklearn.svm.LinearSVC documentation for description of model params.
model_params:
    penalty: l2
    loss: squared_hinge
    dual: True
    tol: 0.0001
    C: 1.0
    multi_class: ovr
    fit_intercept: True
    intercept_scaling: 1
    class_weight: null
    verbose: 0
    random_state: null
    max_iter: 1000